[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NautyGraphs = "7509a0a4-015a-4167-b44b-0799a1a2605e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ReactionNetworkImporters = "b4db0fb7-de2a-5028-82bf-5021f5cfa881"
SIAN = "cf7bdac0-b945-4905-b5ad-bc3f1a757483"
StructuralIdentifiability = "220ca800-aa68-49bb-acd8-6037fa93a544"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
